package ru.createsmart.artopos.feature.discover.util

import android.content.Context
import ru.createsmart.artopos.feature.discover.R

object FilterNameHelper {

    /**
     * Converts a server name to a localized string.
     */
    fun getLocalizedName(context: Context, rawName: String): String {
        val resId = localizedMap[rawName]

        if (resId != null) {
            return context.getString(resId)
        }

        return rawName
    }

    private val localizedMap: Map<String, Int> = mapOf(
        // Classifications
        "Photographs" to R.string.filter_photographs,
        "Prints" to R.string.filter_prints,
        "Drawings" to R.string.filter_drawings,
        "Coins" to R.string.filter_coins,
        "Archival Material" to R.string.filter_archival_material,
        "Paintings" to R.string.filter_paintings,
        "Sculpture" to R.string.filter_sculpture,
        "Vessels" to R.string.filter_vessels,
        "Seals" to R.string.filter_seals,
        "Fragments" to R.string.filter_fragments,
        "Straus Materials" to R.string.filter_straus_materials,
        "Manuscripts" to R.string.filter_manuscripts,
        "Textile Arts" to R.string.filter_textile_arts,
        "Accessories (non-art)" to R.string.filter_accessories_non_art,
        "Artists' Tools" to R.string.filter_artists_tools,
        "Tools and Equipment" to R.string.filter_tools_and_equipment,
        "Multiples" to R.string.filter_multiples,
        "Architectural Elements" to R.string.filter_architectural_elements,
        "Ritual Implements" to R.string.filter_ritual_implements,
        "Jewelry" to R.string.filter_jewelry,
        "Medals and Medallions" to R.string.filter_medals_and_medallions,
        "Lighting Devices" to R.string.filter_lighting_devices,
        "Timepieces" to R.string.filter_timepieces,
        "Books" to R.string.filter_books,
        "Calligraphy" to R.string.filter_calligraphy,
        "Furniture" to R.string.filter_furniture,
        "Albums" to R.string.filter_albums,
        "Artists' Materials" to R.string.filter_artists_materials,
        "Rubbings" to R.string.filter_rubbings,
        "Audiovisual Works" to R.string.filter_audiovisual_works,
        "Plaques" to R.string.filter_plaques,
        "Weapons and Ammunition" to R.string.filter_weapons_and_ammunition,
        "Material Specimens" to R.string.filter_material_specimens,
        "Boxes" to R.string.filter_boxes,
        "Gems" to R.string.filter_gems,
        "Mosaics" to R.string.filter_mosaics,
        "Recreational Artifacts" to R.string.filter_recreational_artifacts,
        "Mirrors" to R.string.filter_mirrors,
        "Paintings with Calligraphy" to R.string.filter_paintings_with_calligraphy,
        "Amulets" to R.string.filter_amulets,
        "Unidentified" to R.string.filter_unidentified,
        "Tokens" to R.string.filter_tokens,
        "Measuring Devices" to R.string.filter_measuring_devices,
        "Riding Equipment" to R.string.filter_riding_equipment,
        "Inscriptions" to R.string.filter_inscriptions,
        "Performance Artifacts" to R.string.filter_performance_artifacts,
        "Stained Glass" to R.string.filter_stained_glass,
        "Armor" to R.string.filter_armor,
        "Brick Stamps" to R.string.filter_brick_stamps,
        "Furnishings" to R.string.filter_furnishings,
        "Tablets" to R.string.filter_tablets,
        "Portfolios" to R.string.filter_portfolios,
        "Cameos" to R.string.filter_cameos,
        "Musical Instruments" to R.string.filter_musical_instruments,
        "Graphic Design" to R.string.filter_graphic_design,
        "Frames" to R.string.filter_frames,
        "Models" to R.string.filter_models,
        "Containers" to R.string.filter_containers,
        "Documents" to R.string.filter_documents,
        "Casts" to R.string.filter_casts,
        "Paintings with Text" to R.string.filter_paintings_with_text,
        "Text" to R.string.filter_text,
        // Centuries
        "20th century" to R.string.filter_20th_century,
        "19th century" to R.string.filter_19th_century,
        "18th century" to R.string.filter_18th_century,
        "17th century" to R.string.filter_17th_century,
        "16th century" to R.string.filter_16th_century,
        "21st century" to R.string.filter_21st_century,
        "4th century BCE" to R.string.filter_4th_century_bce,
        "3rd century CE" to R.string.filter_3rd_century_ce,
        "15th century" to R.string.filter_15th_century,
        "3rd century BCE" to R.string.filter_3rd_century_bce,
        "2nd century CE" to R.string.filter_2nd_century_ce,
        "1st century CE" to R.string.filter_1st_century_ce,
        "5th century BCE" to R.string.filter_5th_century_bce,
        "2nd century BCE" to R.string.filter_2nd_century_bce,
        "1st century BCE" to R.string.filter_1st_century_bce,
        "13th century" to R.string.filter_13th_century,
        "12th century" to R.string.filter_12th_century,
        "4th century CE" to R.string.filter_4th_century_ce,
        "6th century" to R.string.filter_6th_century,
        "8th century" to R.string.filter_8th_century,
        "6th century BCE" to R.string.filter_6th_century_bce,
        "14th century" to R.string.filter_14th_century,
        "7th century" to R.string.filter_7th_century,
        "5th century CE" to R.string.filter_5th_century_ce,
        "11th century" to R.string.filter_11th_century,
        "10th century" to R.string.filter_10th_century,
        "11th century BCE" to R.string.filter_11th_century_bce,
        "8th century BCE" to R.string.filter_8th_century_bce,
        "10th century BCE" to R.string.filter_10th_century_bce,
        "12th century BCE" to R.string.filter_12th_century_bce,
        "3rd millennium BCE" to R.string.filter_3rd_millennium_bce,
        "14th century BCE" to R.string.filter_14th_century_bce,
        "13th century BCE" to R.string.filter_13th_century_bce,
        "7th century BCE" to R.string.filter_7th_century_bce,
        "15th century BCE" to R.string.filter_15th_century_bce,
        "16th century BCE" to R.string.filter_16th_century_bce,
        "9th century BCE" to R.string.filter_9th_century_bce,
        "9th century" to R.string.filter_9th_century,
        "17th century BCE" to R.string.filter_17th_century_bce,
        "18th century BCE" to R.string.filter_18th_century_bce,
        "19th century BCE" to R.string.filter_19th_century_bce,
        "4th millennium BCE" to R.string.filter_4th_millennium_bce,
        "Unidentified century" to R.string.filter_unidentified_century,
        "5th millennium BCE" to R.string.filter_5th_millennium_bce,
        "20th century BCE" to R.string.filter_20th_century_bce,
        "6th millennium BCE" to R.string.filter_6th_millennium_bce,
        // Cultures
        "American" to R.string.filter_american,
        "German" to R.string.filter_german,
        "French" to R.string.filter_french,
        "Italian" to R.string.filter_italian,
        "British" to R.string.filter_british,
        "Japanese" to R.string.filter_japanese,
        "Byzantine" to R.string.filter_byzantine,
        "Greek" to R.string.filter_greek,
        "Chinese" to R.string.filter_chinese,
        "Roman" to R.string.filter_roman,
        "Dutch" to R.string.filter_dutch,
        "Persian" to R.string.filter_persian,
        "Roman Provincial" to R.string.filter_roman_provincial,
        "European" to R.string.filter_european,
        "Flemish" to R.string.filter_flemish,
        "Korean" to R.string.filter_korean,
        "Indian" to R.string.filter_indian,
        "Croatian" to R.string.filter_croatian,
        "Spanish" to R.string.filter_spanish,
        "Egyptian" to R.string.filter_egyptian,
        "Netherlandish" to R.string.filter_netherlandish,
        "Roman Imperial" to R.string.filter_roman_imperial,
        "Swiss" to R.string.filter_swiss,
        "Ottoman" to R.string.filter_ottoman,
        "Unidentified culture" to R.string.filter_unidentified_culture,
        "Roman Republican" to R.string.filter_roman_republican,
        "Austrian" to R.string.filter_austrian,
        "Russian" to R.string.filter_russian,
        "Mexican" to R.string.filter_mexican,
        "Islamic" to R.string.filter_islamic,
        "Coptic" to R.string.filter_coptic,
        "Mycenaean" to R.string.filter_mycenaean,
        "Etruscan" to R.string.filter_etruscan,
        "Brazilian" to R.string.filter_brazilian,
        "Thai" to R.string.filter_thai,
        "Central Asian" to R.string.filter_central_asian,
        "Canadian" to R.string.filter_canadian,
        "English" to R.string.filter_english,
        "Arab" to R.string.filter_arab,
        "Cuban" to R.string.filter_cuban,
        "Scottish" to R.string.filter_scottish,
        "Iranian" to R.string.filter_iranian,
        "Norwegian" to R.string.filter_norwegian,
        "Peruvian" to R.string.filter_peruvian,
        "Syrian" to R.string.filter_syrian,
        "Anatolian" to R.string.filter_anatolian,
        "Belgian" to R.string.filter_belgian,
        "Italic" to R.string.filter_italic,
        "Swedish" to R.string.filter_swedish,
        "Hellenistic" to R.string.filter_hellenistic,
        "Cypriot" to R.string.filter_cypriot,
        "Jewish" to R.string.filter_jewish,
        "Czech" to R.string.filter_czech,
        "Nepalese" to R.string.filter_nepalese,
        "Turkish" to R.string.filter_turkish,
        "Iberian" to R.string.filter_iberian,
        "Irish" to R.string.filter_irish,
        "Ethiopian" to R.string.filter_ethiopian,
        "Minoan" to R.string.filter_minoan,
        "Polish" to R.string.filter_polish,
        "Tibetan" to R.string.filter_tibetan,
        "Celtic" to R.string.filter_celtic,
        "Graeco-Roman" to R.string.filter_graeco_roman,
        "Punic" to R.string.filter_punic,
        "Sasanian" to R.string.filter_sasanian,
        "Portuguese" to R.string.filter_portuguese,
        "Israeli" to R.string.filter_israeli,
        "Turkic" to R.string.filter_turkic,
        "Cambodian" to R.string.filter_cambodian,
        "Near Eastern" to R.string.filter_near_eastern,
        "Danish" to R.string.filter_danish,
        "Argentinian" to R.string.filter_argentinian,
        "Avar" to R.string.filter_avar,
        "Mughal" to R.string.filter_mughal,
        "Armenian" to R.string.filter_armenian,
        "Australian Aboriginal" to R.string.filter_australian_aboriginal,
        "Uzbek" to R.string.filter_uzbek,
        "Cycladic" to R.string.filter_cycladic,
        "Parthian" to R.string.filter_parthian,
        "Crusader" to R.string.filter_crusader,
        "Early Roman" to R.string.filter_early_roman,
        "Hurrian" to R.string.filter_hurrian,
        "Hungarian" to R.string.filter_hungarian,
        "Colombian" to R.string.filter_colombian,
        "Syro-Hittite" to R.string.filter_syro_hittite,
        "Afghan" to R.string.filter_afghan,
        "Mesopotamian" to R.string.filter_mesopotamian,
        "Australian" to R.string.filter_australian,
        "Moroccan" to R.string.filter_moroccan,
        "Seleucid" to R.string.filter_seleucid,
        "Venezuelan" to R.string.filter_venezuelan,
        "Graeco-Bactrian" to R.string.filter_graeco_bactrian,
        "Philippine" to R.string.filter_philippine,
        "East Asian" to R.string.filter_east_asian,
        "New Zealand" to R.string.filter_new_zealand,
        "Achaemenid" to R.string.filter_achaemenid,
        "Indonesian" to R.string.filter_indonesian,
        "Siculo-Punic" to R.string.filter_siculo_punic,
        "Sumerian" to R.string.filter_sumerian,
        "Uruguayan" to R.string.filter_uruguayan,
        "Indo-Greek" to R.string.filter_indo_greek,
        "Levantine" to R.string.filter_levantine,
        "Pre-Columbian" to R.string.filter_pre_columbian,
        "Vietnamese" to R.string.filter_vietnamese,
        "Neo-Assyrian" to R.string.filter_neo_assyrian,
        "South African" to R.string.filter_south_african,
        "Scythian" to R.string.filter_scythian,
        "Assyrian" to R.string.filter_assyrian,
        "Ostrogoth" to R.string.filter_ostrogoth,
        "Kurdish" to R.string.filter_kurdish,
        "Malian" to R.string.filter_malian,
        "Berber" to R.string.filter_berber,
        "North African" to R.string.filter_north_african,
        "Helladic" to R.string.filter_helladic,
        "Caucasian" to R.string.filter_caucasian,
        "Phoenician" to R.string.filter_phoenician,
        "Serbian" to R.string.filter_serbian,
        "Anglo-Saxon" to R.string.filter_anglo_saxon,
        "Bulgarian" to R.string.filter_bulgarian,
        "Norman" to R.string.filter_norman,
        "Chilean" to R.string.filter_chilean,
        "Gandharan" to R.string.filter_gandharan,
        "Native American" to R.string.filter_native_american,
        "South American" to R.string.filter_south_american,
        "Slovenian" to R.string.filter_slovenian,
        "Bohemian" to R.string.filter_bohemian,
        "Neo-Babylonian" to R.string.filter_neo_babylonian,
        "Samarian" to R.string.filter_samarian,
        "Yugoslav" to R.string.filter_yugoslav,
        "Nigerian" to R.string.filter_nigerian,
        "Burmese" to R.string.filter_burmese,
        "Urartian" to R.string.filter_urartian,
        "African" to R.string.filter_african,
        "Italo-Corinthian" to R.string.filter_italo_corinthian,
        "Finnish" to R.string.filter_finnish,
        "Iraqi" to R.string.filter_iraqi,
        "Spanish, Catalonian" to R.string.filter_spanish_catalonian,
        "Turkmen" to R.string.filter_turkmen,
        "Austro-Hungarian" to R.string.filter_austro_hungarian,
        "Slovakian" to R.string.filter_slovakian,
        "Hispano-Moorish" to R.string.filter_hispano_moorish,
        "Asiatic" to R.string.filter_asiatic,
        "Arabo-Byzantine" to R.string.filter_arabo_byzantine,
        "Central American" to R.string.filter_central_american,
        "Khmer" to R.string.filter_khmer,
        "Palestinian" to R.string.filter_palestinian,
        "Nabataean" to R.string.filter_nabataean,
        "Aztec" to R.string.filter_aztec,
        "Babylonian" to R.string.filter_babylonian,
        "Indo-Scythian" to R.string.filter_indo_scythian,
        "Guatemalan" to R.string.filter_guatemalan,
        "Algerian" to R.string.filter_algerian,
        "Hittite" to R.string.filter_hittite,
        "Neo-Hittite" to R.string.filter_neo_hittite,
        "Philisto-Arabian" to R.string.filter_philisto_arabian,
        "Franco-Flemish" to R.string.filter_franco_flemish,
        "Carthaginian" to R.string.filter_carthaginian,
        "Javanese" to R.string.filter_javanese,
        "Vandalic" to R.string.filter_vandalic,
        "Lydian" to R.string.filter_lydian,
        "Italo-Byzantine" to R.string.filter_italo_byzantine,
        "Sabaean" to R.string.filter_sabaean,
        "Malaysian" to R.string.filter_malaysian,
        "Late Roman" to R.string.filter_late_roman,
        "Neo-Sumerian" to R.string.filter_neo_sumerian,
        "Romanian" to R.string.filter_romanian,
        "Sino-Tibetan" to R.string.filter_sino_tibetan,
        "Himyarite" to R.string.filter_himyarite,
        "Turkistani" to R.string.filter_turkistani,
        "Zimbabwean" to R.string.filter_zimbabwean,
        "Spanish Colonial" to R.string.filter_spanish_colonial,
        "West African" to R.string.filter_west_african,
        "Lycian" to R.string.filter_lycian,
        "Annamese" to R.string.filter_annamese,
        "South Asian" to R.string.filter_south_asian,
        "Sri Lankan" to R.string.filter_sri_lankan,
        "Villanovan" to R.string.filter_villanovan,
        "Amlash" to R.string.filter_amlash,
        "Haitian" to R.string.filter_haitian,
        "Puerto Rican" to R.string.filter_puerto_rican,
        "Mongolian" to R.string.filter_mongolian,
        "Pakistani" to R.string.filter_pakistani,
        "Plains Indian" to R.string.filter_plains_indian,
        "Viking" to R.string.filter_viking,
        "Uruk" to R.string.filter_uruk,
        "Graeco-Phoenician" to R.string.filter_graeco_phoenician,
        "Tyrolean" to R.string.filter_tyrolean,
        "Olmec" to R.string.filter_olmec,
        "Costa Rican" to R.string.filter_costa_rican,
        "Mixtec" to R.string.filter_mixtec,
        "Nicaraguan" to R.string.filter_nicaraguan,
        "Semitic" to R.string.filter_semitic,
        "Teotihuacan" to R.string.filter_teotihuacan,
        "Deccani" to R.string.filter_deccani,
        "Sudanese" to R.string.filter_sudanese,
        "Ceylonese" to R.string.filter_ceylonese,
        "Dalmatian" to R.string.filter_dalmatian,
        "Unknown culture" to R.string.filter_unknown_culture,
        "Akkadian" to R.string.filter_akkadian,
        "Maltese" to R.string.filter_maltese,
        "Macedonian" to R.string.filter_macedonian,
        "Azerbaijan" to R.string.filter_azerbaijan,
        "German-Brazilian" to R.string.filter_german_brazilian,
        "Congolese" to R.string.filter_congolese,
        "Germanic" to R.string.filter_germanic,
        "Dogon" to R.string.filter_dogon,
        "Mayan" to R.string.filter_mayan,
        "Graeco-Scythian" to R.string.filter_graeco_scythian,
        "Graeco-Persian" to R.string.filter_graeco_persian,
        "Judaean" to R.string.filter_judaean,
        "Meroitic" to R.string.filter_meroitic,
        "North American" to R.string.filter_north_american,
        "Sardinian" to R.string.filter_sardinian,
        "Turkistan" to R.string.filter_turkistan,
        "Kushite" to R.string.filter_kushite,
        "Yemeni" to R.string.filter_yemeni,
        "East African" to R.string.filter_east_african,
        "Elamite" to R.string.filter_elamite,
        "Celto-Iberian" to R.string.filter_celto_iberian,
        "Southeast Asian" to R.string.filter_southeast_asian,
        "Kuba" to R.string.filter_kuba,
        "Faliscan" to R.string.filter_faliscan,
        "Ukrainian" to R.string.filter_ukrainian,
        "Unspecified Islamic" to R.string.filter_unspecified_islamic,
        "Lebanese" to R.string.filter_lebanese,
        "Mittanian" to R.string.filter_mittanian,
        "Lithuanian" to R.string.filter_lithuanian,
        "Kongo" to R.string.filter_kongo,
        "Honduran" to R.string.filter_honduran,
        "Fang" to R.string.filter_fang,
        "Slavic" to R.string.filter_slavic,
        "Kazakh" to R.string.filter_kazakh,
        "Tusayan" to R.string.filter_tusayan,
        "Arabian" to R.string.filter_arabian,
        "Bhutanese" to R.string.filter_bhutanese,
        "Polynesian" to R.string.filter_polynesian,
        "Hispano-Carthaginian" to R.string.filter_hispano_carthaginian,
        "Graeco-Palestinian" to R.string.filter_graeco_palestinian,
        "Arabo-Sassanian" to R.string.filter_arabo_sassanian,
        "Bactrian" to R.string.filter_bactrian,
        "Frankish" to R.string.filter_frankish,
        "Kissi" to R.string.filter_kissi,
        "Kuba (Bushongo)" to R.string.filter_kuba_bushongo,
        "Benin" to R.string.filter_benin,
        "Aksumite" to R.string.filter_aksumite,
        "Singhalese" to R.string.filter_singhalese,
        "Ubaid" to R.string.filter_ubaid,
        "Baule" to R.string.filter_baule,
        "Central African" to R.string.filter_central_african,
        "Gallo-Roman" to R.string.filter_gallo_roman,
        "Hispano-Flemish" to R.string.filter_hispano_flemish,
        "Hispano-Philippine" to R.string.filter_hispano_philippine,
        "Nuragic" to R.string.filter_nuragic,
        "Sino-Scythian" to R.string.filter_sino_scythian,
        "South Arabian" to R.string.filter_south_arabian,
        "(not assigned)" to R.string.filter_not_assigned,
    )
}
